-- MySQL Script generated by MySQL Workbench
-- Wed Mar 15 18:50:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Basket` (
  `idBasket` CHAR(15) NOT NULL,
  `order` CHAR(4) NULL,
  `pizza` CHAR(5) NULL,
  `availability` TINYINT NULL,
  `quantityItems` INT NULL,
  PRIMARY KEY (`idBasket`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idBasket_UNIQUE` ON `mydb`.`Basket` (`idBasket` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizza` (
  `pizzaName` CHAR(15) NOT NULL,
  `pizzaDescription` VARCHAR(45) NULL,
  `memoryAid` CHAR(10) NULL,
  `size` CHAR(10) NULL,
  `type` CHAR(10) NULL,
  `Basket_idBasket` CHAR(15) NOT NULL,
  PRIMARY KEY (`pizzaName`, `Basket_idBasket`),
  CONSTRAINT `fk_Pizza_Basket1`
    FOREIGN KEY (`Basket_idBasket`)
    REFERENCES `mydb`.`Basket` (`idBasket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `pizzaName_UNIQUE` ON `mydb`.`Pizza` (`pizzaName` ASC) VISIBLE;

CREATE INDEX `fk_Pizza_Basket1_idx` ON `mydb`.`Pizza` (`Basket_idBasket` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredient` (
  `id` INT UNSIGNED NOT NULL,
  `name` CHAR(10) NULL,
  `unitIngredients` CHAR(5) NULL,
  `Pizza_pizzaName` CHAR(15) NOT NULL,
  `Pizza_Basket_idBasket` CHAR(15) NOT NULL,
  PRIMARY KEY (`id`, `Pizza_pizzaName`, `Pizza_Basket_idBasket`),
  CONSTRAINT `fk_Ingredient_Pizza1`
    FOREIGN KEY (`Pizza_pizzaName` , `Pizza_Basket_idBasket`)
    REFERENCES `mydb`.`Pizza` (`pizzaName` , `Basket_idBasket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Ingredient_Pizza1_idx` ON `mydb`.`Ingredient` (`Pizza_pizzaName` ASC, `Pizza_Basket_idBasket` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`MemoryAid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MemoryAid` (
  `idMemoryAid` TINYINT(20) NOT NULL,
  `recipe` VARCHAR(100) NULL,
  `ingredientQuantity` VARCHAR(45) NULL,
  `steps` CHAR(20) NULL,
  `Pizza_pizzaName` CHAR(15) NOT NULL,
  `Pizza_Basket_idBasket` CHAR(15) NOT NULL,
  `Ingredient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMemoryAid`, `Pizza_pizzaName`, `Pizza_Basket_idBasket`, `Ingredient_id`),
  CONSTRAINT `fk_MemoryAid_Pizza1`
    FOREIGN KEY (`Pizza_pizzaName` , `Pizza_Basket_idBasket`)
    REFERENCES `mydb`.`Pizza` (`pizzaName` , `Basket_idBasket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MemoryAid_Ingredient1`
    FOREIGN KEY (`Ingredient_id`)
    REFERENCES `mydb`.`Ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMemoryAid_UNIQUE` ON `mydb`.`MemoryAid` (`idMemoryAid` ASC) VISIBLE;

CREATE INDEX `fk_MemoryAid_Pizza1_idx` ON `mydb`.`MemoryAid` (`Pizza_pizzaName` ASC, `Pizza_Basket_idBasket` ASC) VISIBLE;

CREATE INDEX `fk_MemoryAid_Ingredient1_idx` ON `mydb`.`MemoryAid` (`Ingredient_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stock` (
  `idStock` INT NOT NULL,
  `ingredientAvailability` TINYINT NULL,
  `inventory` CHAR(20) NULL,
  `unitPrice` INT NULL,
  `Restaurant_idRestaurant` INT NOT NULL,
  `Restaurant_Adress_streetNumber` INT NOT NULL,
  `Restaurant_Adress_streetName` CHAR(30) NOT NULL,
  `Restaurant_Adress_city` CHAR(20) NOT NULL,
  `Restaurant_Adress_postCode` INT NOT NULL,
  `Ingredient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idStock`, `Restaurant_idRestaurant`, `Restaurant_Adress_streetNumber`, `Restaurant_Adress_streetName`, `Restaurant_Adress_city`, `Restaurant_Adress_postCode`, `Ingredient_id`),
  CONSTRAINT `fk_Stock_Restaurant1`
    FOREIGN KEY (`Restaurant_idRestaurant` , `Restaurant_Adress_streetNumber` , `Restaurant_Adress_streetName` , `Restaurant_Adress_city` , `Restaurant_Adress_postCode`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant` , `Adress_streetNumber` , `Adress_streetName` , `Adress_city` , `Adress_postCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_Ingredient1`
    FOREIGN KEY (`Ingredient_id`)
    REFERENCES `mydb`.`Ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adress` (
  `streetNumber` INT NOT NULL,
  `streetName` CHAR(30) NOT NULL,
  `city` CHAR(20) NOT NULL,
  `postCode` INT NOT NULL,
  PRIMARY KEY (`streetNumber`, `streetName`, `city`, `postCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant` (
  `idRestaurant` INT NOT NULL,
  `name` VARCHAR(20) NULL,
  `adress` VARCHAR(30) NULL,
  `employee` CHAR(10) NULL,
  `Adress_streetNumber` INT NOT NULL,
  `Adress_streetName` CHAR(30) NOT NULL,
  `Adress_city` CHAR(20) NOT NULL,
  `Adress_postCode` INT NOT NULL,
  PRIMARY KEY (`idRestaurant`, `Adress_streetNumber`, `Adress_streetName`, `Adress_city`, `Adress_postCode`),
  CONSTRAINT `fk_Restaurant_Adress`
    FOREIGN KEY (`Adress_streetNumber` , `Adress_streetName` , `Adress_city` , `Adress_postCode`)
    REFERENCES `mydb`.`Adress` (`streetNumber` , `streetName` , `city` , `postCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Restaurant_Adress_idx` ON `mydb`.`Restaurant` (`Adress_streetNumber` ASC, `Adress_streetName` ASC, `Adress_city` ASC, `Adress_postCode` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stock` (
  `idStock` INT NOT NULL,
  `ingredientAvailability` TINYINT NULL,
  `inventory` CHAR(20) NULL,
  `unitPrice` INT NULL,
  `Restaurant_idRestaurant` INT NOT NULL,
  `Restaurant_Adress_streetNumber` INT NOT NULL,
  `Restaurant_Adress_streetName` CHAR(30) NOT NULL,
  `Restaurant_Adress_city` CHAR(20) NOT NULL,
  `Restaurant_Adress_postCode` INT NOT NULL,
  `Ingredient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idStock`, `Restaurant_idRestaurant`, `Restaurant_Adress_streetNumber`, `Restaurant_Adress_streetName`, `Restaurant_Adress_city`, `Restaurant_Adress_postCode`, `Ingredient_id`),
  CONSTRAINT `fk_Stock_Restaurant1`
    FOREIGN KEY (`Restaurant_idRestaurant` , `Restaurant_Adress_streetNumber` , `Restaurant_Adress_streetName` , `Restaurant_Adress_city` , `Restaurant_Adress_postCode`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant` , `Adress_streetNumber` , `Adress_streetName` , `Adress_city` , `Adress_postCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_Ingredient1`
    FOREIGN KEY (`Ingredient_id`)
    REFERENCES `mydb`.`Ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Stock_Restaurant1_idx` ON `mydb`.`Stock` (`Restaurant_idRestaurant` ASC, `Restaurant_Adress_streetNumber` ASC, `Restaurant_Adress_streetName` ASC, `Restaurant_Adress_city` ASC, `Restaurant_Adress_postCode` ASC) VISIBLE;

CREATE INDEX `fk_Stock_Ingredient1_idx` ON `mydb`.`Stock` (`Ingredient_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerEmail` CHAR(20) NOT NULL,
  `CustomerName` CHAR(10) NULL,
  `CustomerFirstName` CHAR(10) NULL,
  `CustomerAddress` VARCHAR(45) NULL,
  `CustomerPhoneN` INT NULL,
  `login` CHAR(20) NULL,
  `passWord` CHAR(20) NULL,
  `orderHistory` VARCHAR(200) NULL,
  PRIMARY KEY (`CustomerEmail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idOrder` CHAR(15) NOT NULL,
  `quantity` INT NULL,
  `hour` TIME NULL,
  `date` DATE NULL,
  `status` CHAR(15) NULL,
  `paymentMethod` CHAR(15) NULL,
  `deliveryMode` CHAR(15) NULL,
  `Basket_idBasket` CHAR(15) NOT NULL,
  PRIMARY KEY (`idOrder`, `Basket_idBasket`),
  CONSTRAINT `fk_Order_Basket1`
    FOREIGN KEY (`Basket_idBasket`)
    REFERENCES `mydb`.`Basket` (`idBasket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idOrder_UNIQUE` ON `mydb`.`Order` (`idOrder` ASC) VISIBLE;

CREATE INDEX `fk_Order_Basket1_idx` ON `mydb`.`Order` (`Basket_idBasket` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `emailAddress` CHAR(20) NOT NULL,
  `job` VARCHAR(45) NULL,
  `name` CHAR(20) NULL,
  `login` VARCHAR(45) NULL,
  `passWord:` VARCHAR(45) NULL,
  `Restaurant_idRestaurant` INT NOT NULL,
  `Restaurant_Adress_streetNumber` INT NOT NULL,
  `Restaurant_Adress_streetName` CHAR(30) NOT NULL,
  `Restaurant_Adress_city` CHAR(20) NOT NULL,
  `Restaurant_Adress_postCode` INT NOT NULL,
  PRIMARY KEY (`emailAddress`, `Restaurant_idRestaurant`, `Restaurant_Adress_streetNumber`, `Restaurant_Adress_streetName`, `Restaurant_Adress_city`, `Restaurant_Adress_postCode`),
  CONSTRAINT `fk_Employee_Restaurant1`
    FOREIGN KEY (`Restaurant_idRestaurant` , `Restaurant_Adress_streetNumber` , `Restaurant_Adress_streetName` , `Restaurant_Adress_city` , `Restaurant_Adress_postCode`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant` , `Adress_streetNumber` , `Adress_streetName` , `Adress_city` , `Adress_postCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `emailAddress_UNIQUE` ON `mydb`.`Employee` (`emailAddress` ASC) VISIBLE;

CREATE UNIQUE INDEX `login_UNIQUE` ON `mydb`.`Employee` (`login` ASC) VISIBLE;

CREATE INDEX `fk_Employee_Restaurant1_idx` ON `mydb`.`Employee` (`Restaurant_idRestaurant` ASC, `Restaurant_Adress_streetNumber` ASC, `Restaurant_Adress_streetName` ASC, `Restaurant_Adress_city` ASC, `Restaurant_Adress_postCode` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_has_Adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_has_Adress` (
  `Customer_CustomerEmail` CHAR(20) NOT NULL,
  `Adress_streetNumber` INT NOT NULL,
  `Adress_streetName` CHAR(30) NOT NULL,
  `Adress_city` CHAR(20) NOT NULL,
  `Adress_postCode` INT NOT NULL,
  PRIMARY KEY (`Customer_CustomerEmail`, `Adress_streetNumber`, `Adress_streetName`, `Adress_city`, `Adress_postCode`),
  CONSTRAINT `fk_Customer_has_Adress_Customer1`
    FOREIGN KEY (`Customer_CustomerEmail`)
    REFERENCES `mydb`.`Customer` (`CustomerEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Adress_Adress1`
    FOREIGN KEY (`Adress_streetNumber` , `Adress_streetName` , `Adress_city` , `Adress_postCode`)
    REFERENCES `mydb`.`Adress` (`streetNumber` , `streetName` , `city` , `postCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Customer_has_Adress_Adress1_idx` ON `mydb`.`Customer_has_Adress` (`Adress_streetNumber` ASC, `Adress_streetName` ASC, `Adress_city` ASC, `Adress_postCode` ASC) VISIBLE;

CREATE INDEX `fk_Customer_has_Adress_Customer1_idx` ON `mydb`.`Customer_has_Adress` (`Customer_CustomerEmail` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Order_has_Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_has_Customer` (
  `Order_idOrder` CHAR(15) NOT NULL,
  `Customer_CustomerEmail` CHAR(20) NOT NULL,
  PRIMARY KEY (`Order_idOrder`, `Customer_CustomerEmail`),
  CONSTRAINT `fk_Order_has_Customer_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Customer_Customer1`
    FOREIGN KEY (`Customer_CustomerEmail`)
    REFERENCES `mydb`.`Customer` (`CustomerEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Order_has_Customer_Customer1_idx` ON `mydb`.`Order_has_Customer` (`Customer_CustomerEmail` ASC) VISIBLE;

CREATE INDEX `fk_Order_has_Customer_Order1_idx` ON `mydb`.`Order_has_Customer` (`Order_idOrder` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
